services:
    postgres:
        container_name: '${CONTEXT_NAME}_postgres'
        image: postgres:${POSTGRES_VERSION}
        environment:
          - POSTGRES_DB=${POSTGRES_DB_NAME}
          - POSTGRES_USER=${POSTGRES_DB_USER}
          - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
          - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
          - ${CONTEXT_DIR_WEX}postgres/data:/var/lib/postgresql/data
          - ${CONTEXT_DIR_WEX}postgres/dumps:/var/www/dumps
        extends:
            file: ${SERVICE_DEFAULT_YML_ENV}
            service: default