services:
    mysql_8:
        container_name: '${APP_NAME_INTERNAL}_mysql'
        image: mysql:8.0.32
        environment:
            - MYSQL_DATABASE=${MYSQL_DB_NAME}
            - MYSQL_PASSWORD=${MYSQL_DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_DB_PASSWORD}
        volumes:
            - ${APP_PATH_WEX}mysql/data:/var/lib/mysql
            - ${APP_PATH_WEX}mysql/dumps:/var/www/dumps
            - ${APP_PATH_WEX}tmp/mysql.cnf:/tmp/mysql.cnf
        extends:
            file: ${WEX_COMPOSE_YML_DEFAULT}
            service: default